import { NextRequest, NextResponse } from 'next/server';
import { connectToDatabase } from '@/lib/mongodb';
import Order from '@/models/Order';
import Product from '@/models/Product';
import PosCartSession from '@/models/PosCartSession';

export const dynamic = 'force-dynamic';

export async function POST(req: NextRequest) {
  try {
    await connectToDatabase();
    const body = await req.json();

    const {
      seller_id = 1,
      user_id = 0,
      customer_name = 'Walk-in Customer',
      customer_mobile = '',
      cart_items = [],
      items = [],
      subtotal = 0,
      tax = 0,
      additional_charges = [],
      additional_discount = 0,
      payment_method = 'CASH',
      session_id,
    } = body;

    const finalCartItems = cart_items.length > 0 ? cart_items : items;
    const orderId = `POS${Date.now()}${Math.floor(Math.random() * 1000)}`;

    const additionalChargesTotal = Array.isArray(additional_charges)
      ? additional_charges.reduce((sum: number, c: any) => sum + (Number(c.amount) || 0), 0)
      : Number(additional_charges) || 0;

    const finalTotal = Math.max(0, subtotal + tax + additionalChargesTotal - additional_discount);

    // Create Order document
    const newOrder = await Order.create({
      order_id: orderId,
      user_id: Number(user_id) || 0,
      seller_id: Number(seller_id) || 1,
      items: finalCartItems.map((item: any) => ({
        product_id: item.product_id || item.id || item._id,
        variant_id: item.variant_id || item.id || 1,
        product_name: item.name || item.product_name || item.title,
        variant_title: item.variant_title || 'Default',
        price: item.price,
        discounted_price: item.discounted_price || item.price,
        quantity: item.quantity,
        image: item.image || '',
        seller_id: Number(seller_id) || 1,
      })),
      subtotal,
      delivery_charge: 0,
      service_fee: additionalChargesTotal,
      tax_amount: tax,
      discount_amount: additional_discount,
      wallet_amount_used: 0,
      total_amount: finalTotal,
      payment_method: (payment_method || 'cash').toLowerCase(),
      payment_status: 'paid',
      order_status: 'delivered',
      delivery_timeslot: 'Immediate Counter Pickup',
      delivery_address: {
        title: customer_name,
        address_line: 'Store Counter Pickup (POS)',
        city: 'Lagos',
        phone: customer_mobile || '0000000000',
      },
      delivery_pin: '0000',
      order_notes: `POS Order generated by Admin/Cashier. Payment: ${payment_method}`,
    });

    // Update stock for purchased products
    for (const item of finalCartItems) {
      try {
        const prodId = item.product_id || item.id || item._id;
        if (prodId) {
          const prod = await Product.findById(prodId);
          if (prod && prod.variants && prod.variants.length > 0) {
            const currentStock = prod.variants[0].stock || 0;
            prod.variants[0].stock = Math.max(0, currentStock - item.quantity);
            await prod.save();
          }
        }
      } catch (err) {
        console.warn('POS stock update warning:', err);
      }
    }

    // Delete cart session if hold tab session ID provided
    if (session_id) {
      await PosCartSession.deleteOne({ session_id }).catch(() => null);
    }

    return NextResponse.json({
      success: true,
      message: 'POS Order placed successfully',
      order_id: orderId,
      order: newOrder,
    });
  } catch (error: any) {
    console.error('POS Checkout error:', error);
    return NextResponse.json({ success: false, message: error.message }, { status: 500 });
  }
}
